apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k8s-check-expiration
  namespace: kube-system
spec:
    schedule: "0 10 * * *"
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: k8s-check-expiration
              image: idock.daumkakao.io/steve_kim/k8s_check_expiration:v0.1
              env:
              - name: EXDAY
                value: "90"
              - name: WTID
                value: "12216"
              command: ["/bin/sh"]
              args: ["-c", "/check_expiration.sh noti"]
              volumeMounts:
              - mountPath: /etc/kubernetes/pki
                name: pki
                readOnly: true
            restartPolicy: OnFailure
            nodeSelector:
               node-role.kubernetes.io/master: ""
            tolerations:
             - effect: NoSchedule
               operator: Exists
            hostNetwork: true
            volumes:
            - name: pki
              hostPath:
                path: /etc/kubernetes/pki
                type: DirectoryOrCreate